### ISSUE TITLE
Allow logging to file and docker console output as JSON

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-payment-to-order-processor#4]
By default should log to both streams.

**Comment by butenkor** [comment]
@mht-dotsource what is the state of this issue?

**Comment by butenkor** [comment]
http://sdqali.in/blog/2016/06/30/json-logging-for-spring-applications/

**Comment by heshamMassoud** [comment]
released in https://github.com/commercetools/commercetools-payment-to-order-processor/releases/tag/v1.2.0
